### ISSUE TITLE
Move items in/out of groups

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#244] opened 2021-02-15 07:52 UTC
It would be nice to drag-and-drop questions in or out of the groups. Currently I think I have to delete the question and create it again outside the group. See printscreen:
![image](https://user-images.githubusercontent.com/77841246/107919088-1043e180-6f6b-11eb-8066-f9f2529585da.png)

**Comment by losolio** [comment] 2021-02-16 09:26
Duplicate of #203.

**Closed by losolio** 2021-02-16 09:26 UTC
Labels: triage-needed
